services:
  porcupine:
    image: porcupine:latest
    ports:
      - 80:80
  tickets_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
       - ./init-scripts:/docker-entrypoint-initdb.d
       - db_data:/var/lib/postgresql/data

volumes:
   db_data:
