services:
  directory_db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
       - ./init-scripts:/docker-entrypoint-initdb.d
       - db_data:/var/lib/postgresql/data

volumes:
   db_data:
